backend:
  name: github
  repo: Luana3333333/BugCatalogue
  branch: main

media_folder: "images/uploads"

collections:
  - name: "kaefer"
    label: "Käfer"
    folder: "_kaefer"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Familie", name: "familie", widget: "string" }
      - { label: "Beschreibung", name: "beschreibung", widget: "text" }
      - { label: "Bild", name: "bild", widget: "image" }
      - {
          label: "Detailbild",
          name: "detailbild",
          widget: "image",
          required: false,
        }
      - {
          label: "Bildbeschreibung",
          name: "bildbeschreibung",
          widget: "string",
          required: false,
        }
      - {
          label: "Kategorie",
          name: "kategorie",
          widget: "select",
          options: ["Geflügelte Käfer", "Gepanzerte Käfer", "Rüsselkäfer"],
        }
