backend:
  name: github
  repo: Luana3333333/BugCatalogue
  branch: main
  auth_type: implicit
  base_url: https://api.netlify.com
auth_endpoint: https://api.netlify.com

media_folder: "images/uploads"

collections:
  - name: "kaefer"
    label: "Käfer"
    folder: "_kaefer"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Familie", name: "familie", widget: "string" }
      - { label: "Beschreibung", name: "beschreibung", widget: "text" }
      - { label: "Bild", name: "bild", widget: "image" }
      - {
          label: "Kategorie",
          name: "kategorie",
          widget: "select",
          options: ["Geflügelte Käfer", "Gepanzerte Käfer", "Rüsselkäfer"],
        }
